version: '2'
services:
  web:
    image: app
    ports:
      - "3000:3000"
    links:
      - db
      - redisdb
      - ethereum
    environment:
      SEQ_DB: fitcoin
      SEQ_USER: docker
      SEQ_PW: docker
      WORKER_1_SETTIMEOUT: 30000
      DATABASE_URL: postgres://docker:docker@db:5432/fitcoin
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fitcoin
  redisdb:
    image: redis
    

  ethereum:
    image: apantelides/eth
    ports:
      - "3002:3002"
    links:
      - testrpc
    # volumes:
    #   - ../ethereumService:/usr/src/app
  testrpc:
    image: apantelides/testrpc
    ports: 
      - "8545:8545"

